#! /bin/sh

echo -n "Starting Kenwood System Manager: "

if [ -f /usr/local/TS-990/bin/system_manager/sys_man.main.new ]
then
  echo "Updating System Manager"
  rm /usr/local/TS-990/bin/system_manager/sys_man.main
  mv /usr/local/TS-990/bin/system_manager/sys_man.main.new /usr/local/TS-990/bin/system_manager/sys_man.main
  if [ $? -eq 0 ]
  then
    echo "Complete"
  fi
fi

/usr/local/TS-990/bin/system_manager/sys_man.main &
echo "done"

